definitions:
  structtypes.JSONResult:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: getneko api doc
  version: "1.0"
paths:
  /v1/chacklowversion:
    get:
      consumes:
      - application/json
      description: 比较客户端与服务器的版本号
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取客户端最低版本
      tags:
      - 客户端信息
swagger: "2.0"
