definitions:
  structtypes.Createproject:
    properties:
      name:
        description: 名字
        type: string
      tokens:
        description: 用户token
        type: string
      username:
        description: 用户名
        type: string
    required:
    - name
    - tokens
    - username
    type: object
  structtypes.Delproject:
    properties:
      name:
        description: 名字
        type: string
      tokens:
        description: 用户token
        type: string
      username:
        description: 用户名
        type: string
    required:
    - name
    - tokens
    - username
    type: object
  structtypes.Getpermissionlist:
    properties:
      projectname:
        description: 项目名
        type: string
      tokens:
        description: 用户token
        type: string
      username:
        description: 用户名
        type: string
    required:
    - projectname
    - tokens
    - username
    type: object
  structtypes.Getpermissionlistres:
    properties:
      levels:
        type: integer
      userID:
        type: integer
      username:
        type: string
    type: object
  structtypes.JSONResult:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  structtypes.UserLogin:
    properties:
      language:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - language
    - password
    - username
    type: object
  structtypes.UserRegReq:
    properties:
      email:
        type: string
      language:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - language
    - password
    - username
    type: object
  structtypes.Usersearchres:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: getneko api doc
  version: "1.0"
paths:
  /v1/chacklowversion:
    get:
      consumes:
      - application/json
      description: 比较客户端与服务器的版本号
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: 获取客户端最低版本
      tags:
      - 客户端信息
  /v1/createproject:
    post:
      consumes:
      - application/json
      description: 目前暂时没有做权限
      parameters:
      - description: project info
        in: body
        name: UserLogin
        required: true
        schema:
          $ref: '#/definitions/structtypes.Createproject'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: 创建项目
      tags:
      - 项目操作
  /v1/delproject:
    post:
      consumes:
      - application/json
      description: 只要创建者才能删除
      parameters:
      - description: project info
        in: body
        name: UserLogin
        required: true
        schema:
          $ref: '#/definitions/structtypes.Delproject'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: 删除项目
      tags:
      - 项目操作
  /v1/getpermissionlist:
    post:
      consumes:
      - application/json
      description: 需要管理员权限
      parameters:
      - description: project info
        in: body
        name: UserLogin
        required: true
        schema:
          $ref: '#/definitions/structtypes.Getpermissionlist'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/structtypes.Getpermissionlistres'
                  type: array
              type: object
      summary: 获取项目权限表
      tags:
      - 权限操作
  /v1/userlogin:
    post:
      consumes:
      - application/json
      description: 用户登陆api
      parameters:
      - description: user info
        in: body
        name: UserLogin
        required: true
        schema:
          $ref: '#/definitions/structtypes.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: 用户登陆
      tags:
      - 用户操作
  /v1/userreg:
    post:
      consumes:
      - application/json
      description: 用户注册api
      parameters:
      - description: user info
        in: body
        name: UserRegReq
        required: true
        schema:
          $ref: '#/definitions/structtypes.UserRegReq'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  type: string
              type: object
      summary: 用户注册
      tags:
      - 用户操作
  /v1/usersearch:
    get:
      consumes:
      - application/json
      description: 无需鉴权
      parameters:
      - in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/structtypes.JSONResult'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/structtypes.Usersearchres'
                  type: array
              type: object
      summary: 模糊查询用户
      tags:
      - 用户操作
swagger: "2.0"
